// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEeKIT_k9sdEcCPw_sW8Lh7U45KnwkM7s',
    appId: '1:557212469555:web:fd10cd12794c297ea71646',
    messagingSenderId: '557212469555',
    projectId: 'gateappsgp',
    authDomain: 'gateappsgp.firebaseapp.com',
    storageBucket: 'gateappsgp.appspot.com',
    measurementId: 'G-RGWNKWPY1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJDOEZSK8TXIXx6Z-wjokyj1yvjDfIz3M',
    appId: '1:557212469555:android:2a4efbf96d7b3a14a71646',
    messagingSenderId: '557212469555',
    projectId: 'gateappsgp',
    storageBucket: 'gateappsgp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_vDNYj5l1vcmvVP_81hns8NTvQuCgKXw',
    appId: '1:557212469555:ios:f669f0fded112b51a71646',
    messagingSenderId: '557212469555',
    projectId: 'gateappsgp',
    storageBucket: 'gateappsgp.appspot.com',
    androidClientId: '557212469555-8p1en2arrgd6f2hbej7at8ov6cqe925k.apps.googleusercontent.com',
    iosClientId: '557212469555-19qn3qed2leg0n2ub4f54vb296g50qn4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
